### ISSUE TITLE
Spuštění jupyter notebooku v rámci skriptu

### ISSUE THREAD

**Issue by Hexex36** [MFVS/kontrola-rozvrhu-extended#5]
Potom, co uživatel nakliká všechno do frontendu, potom by se měl spustit řetěz skriptů (fetchnutí CSV souborů, bombátor, addony podle pohledu). Jak se tohle dělá? Bash/Powershell skript? Jde přes python nějak spustit Jupyter notebook?

**Comment by Hexex36** [comment]
Přes nbformat a nbconvert se do dá nějak udělat.

**Comment by nexovec** [comment]
Doporučuji to napsat přímo do toho streamlitu, bude to pohodlnější než debugovat vygenerované skripty.
